version: '2'

services:
  bmlt:
    image: radius314/bmlt:latest
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mariadb:10.1.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bmlt_root_password
      MYSQL_DATABASE: bmlt
      MYSQL_USER: bmlt_user
      MYSQL_PASSWORD: bmlt_password
